### ISSUE TITLE
演習問題2.13 (a)の解について

### ISSUE THREAD

**Issue by NaCl5alt** [horie-t/DigitalDesignAndComputerArchitecture-Ans#1]
[演習問題2.13 (a)](https://github.com/horie-t/DigitalDesignAndComputerArchitecture-Ans/blob/master/chap2/exercise/2-13.md#a)の解が<img src="https://latex.codecogs.com/gif.latex?Y=AC&plus;BC">となっていますが、正しくは<img src="https://latex.codecogs.com/gif.latex?Y=AC&plus;\bar{B}C">だと思われます。
確認の方よろしくお願いします。

**Comment by horie-t** [comment]
@shouta02jp  ご指摘ありがとうございました。修正しました。
